### ISSUE TITLE
CORS Preflight does not work with JIRA

### ISSUE THREAD

**Issue by dalini** [SecurityRAT/securityrat.github.io#1]
the current JIRA releases do not properly support CORS preflight option requests - therefore an extended setup (e.g. in apache as proxy) is suggested as workaround at the time being - eventually there should be a hint at the documentation regarding this issue:

https://jira.atlassian.com/browse/JRASERVER-59101?focusedCommentId=1007679&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1007679

```    # ALLOW CORS everywhere
    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Max-Age "1000"
    Header always set Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"

    # Return 200 for all OPTIONS CORS preflight requests to the REST API
    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(/rest/api/2/.*)$ $1 [R=200,L]
```

the page: https://securityrat.github.io/int_jira.html should be adopted accordingly.

**Comment by dkefer** [comment]
Hmm, I find those Headers extremely permissive. I find it difficult to recommend them, but will add a link to that issue, thanks!

**Comment by dkefer** [comment]
Added another warning on the website, closing here.
